### ISSUE TITLE
lab7tester.cpp has undefined references to the quickSortLast, Middle, Random, MediumOf3, 

### ISSUE THREAD

**Issue by izhuravlev** [seneca-btp500f19/btp500-f19#10]
@cathyatseneca the tester for lab7 for Asem's group gives out the compiling error:
```
[izhuravlev@mtrx-node01pd lab7]$ cat errw2.txt
/tmp/ccsmAmTo.o: In function `main':
lab7tester.cpp:(.text+0x79): undefined reference to `quickSortLast(int*, int)'
lab7tester.cpp:(.text+0x84): undefined reference to `quickSortMiddle(int*, int)'
lab7tester.cpp:(.text+0x8f): undefined reference to `quickSortMedianOf3(int*, int)'
lab7tester.cpp:(.text+0x9a): undefined reference to `quickSortRandom(int*, int)'
collect2: error: ld returned 1 exit status
```

I believe that the error is in the lab7tester.cpp.

**Comment by cathyatseneca** [comment]
lab7tester.cpp actually doesn't have any calls to this.. I can see that the comment at the top for compilation is wrong but not there isn't a reference to any of these functions for inside the lab7tester itself (you should be able to compile and run the tester as is.... I think this might be a file error within the submitter files, I'll let Asem know.

**Comment by izhuravlev** [comment]
Thank you very much @cathyatseneca, it's all resolved 😃
