### ISSUE TITLE
Typo in A1 disjointsets

### ISSUE THREAD

**Issue by blackHatMonkey** [seneca-btp500f19/btp500-f19#3]
The following are typos where `union` needs to be changed to `unionSets` based on the spec:
https://github.com/seneca-btp500f19/btp500-f19/blob/d828b9bf1502de804b2d05575882e450ac0785c8/a1files/disjointset.h#L14

https://github.com/seneca-btp500f19/btp500-f19/blob/d828b9bf1502de804b2d05575882e450ac0785c8/a1files/disjointset.cpp#L11

**Comment by nnknguyen** [comment]
I think this one is fixed
