### ISSUE TITLE
Possible typo in Assignment 2

### ISSUE THREAD

**Issue by birtony** [seneca-btp500f19/btp500-f19#9]
It has come to my attention that there is likely a typo in Assignment 2 wiki page. In [the `Overview` section](https://github.com/seneca-btp500f19/btp500-f19/wiki/assignment-2#overview) the following sentence says:

> The key in a c++ string.

Whereas it is probably supposed to be:

> The key **_is_** a c++ string.

**Comment by cathyatseneca** [comment]
yep that is a typo.  I'll fix it thanks!
